import type { RuleRecord } from '../../schema'

export const RULES: RuleRecord[] = [
  {
    id: 'signal.spi.drought.severe',
    version: '1.0.0',
    category: 'threshold',
    component: 'external_risk',
    description: 'Severe drought — SPI below -2 indicates extreme rainfall deficit across all agricultural sectors, triggering widespread crop failure and fodder shortage',
    condition: {
      type: 'simple',
      variable: 'spi',
      operator: '<',
      value: -2,
    },
    effect: {
      riskDelta: 30,
      reason: 'SPI below -2 — severe drought conditions. Crop failure likely, groundwater recharge critically low, fodder availability plummeting, and livestock distress imminent',
      recommendedAction: 'Emergency fodder procurement, activate drought relief scheme application (PMFBY crop insurance), reduce herd size if water scarcity is acute, explore alternative feed sources',
      confidence: 'high',
    },
    researchBasis: {
      source: 'India Meteorological Department (IMD) Drought Classification',
      url: 'https://mausam.imd.gov.in/',
      specificFinding: 'SPI < -2 classifies as severe drought — rainfall deficit exceeds 40% of normal. Historically affects 25-30 districts in any given year in India',
      indiaValidation: 'IMD drought classification adopted by NABARD for disaster response triggers — 2014-15 drought in Maharashtra and Karnataka followed SPI < -2 pattern',
      limitations: 'SPI based on rainfall alone — does not capture groundwater depletion or irrigation access which significantly modify actual drought impact',
    },
    testCases: [
      {
        description: 'District with SPI at -2.3 in monsoon season — severe drought triggers',
        inputs: { spi: -2.3 },
        expectedTriggered: true,
        expectedRiskDelta: 30,
        expectedReason: 'SPI below -2 — severe drought conditions',
      },
      {
        description: 'District with SPI at -0.5 — normal rainfall variation',
        inputs: { spi: -0.5 },
        expectedTriggered: false,
      },
    ],
    reviewDate: '2026-07-01',
  },
  {
    id: 'signal.spi.drought.moderate.agriculture',
    version: '1.0.0',
    category: 'threshold',
    component: 'input_cost_pressure',
    sector: 'agriculture',
    description: 'Moderate drought — SPI between -1 and -2 causes fodder shortage, rising input costs, and irrigation dependency in agriculture sector',
    condition: {
      type: 'band',
      variable: 'spi',
      min: -2,
      max: -1,
    },
    effect: {
      riskDelta: 20,
      reason: 'SPI between -1 and -2 — moderate drought. Rainfall deficit 20-40%, crop stress visible, irrigation costs rising, and market fodder prices increasing',
      recommendedAction: 'Switch to drought-resistant crop varieties for next season, optimize irrigation scheduling, explore drip irrigation subsidy under PMKSY, store fodder early before prices peak',
      confidence: 'high',
    },
    researchBasis: {
      source: 'NABARD Drought Impact Assessment Studies',
      url: 'https://www.nabard.org/',
      specificFinding: 'Moderate drought (SPI -1 to -2) increases agriculture input costs 15-25% due to additional irrigation and crop protection measures. Crop yields decline 10-20%',
      indiaValidation: 'NABARD district-level studies in Rajasthan and Maharashtra show 15-25% increase in cultivation costs during moderate drought years',
      limitations: 'Impact varies significantly by irrigation access — rainfed agriculture far more affected than irrigated areas',
    },
    testCases: [
      {
        description: 'Agriculture district with SPI at -1.5 — moderate drought triggers',
        inputs: { spi: -1.5 },
        expectedTriggered: true,
        expectedRiskDelta: 20,
        expectedReason: 'SPI between -1 and -2 — moderate drought',
      },
      {
        description: 'Agriculture district with SPI at -0.8 — below drought threshold',
        inputs: { spi: -0.8 },
        expectedTriggered: false,
      },
    ],
    reviewDate: '2026-07-01',
  },
  {
    id: 'signal.spi.drought.moderate.dairy',
    version: '1.0.0',
    category: 'threshold',
    component: 'input_cost_pressure',
    sector: 'dairy',
    description: 'Dairy fodder shortage — SPI below -1 increases fodder costs and reduces milk yield due to poor pasture quality',
    condition: {
      type: 'simple',
      variable: 'spi',
      operator: '<',
      value: -1,
    },
    effect: {
      riskDelta: 10,
      reason: 'SPI below -1 — moderate drought impacting dairy through fodder shortage. Pasture quality declining, supplementary feed costs rising 10-20%, and milk yield under pressure',
      recommendedAction: 'Source dry fodder and concentrate early before prices spike, explore silage-making for long-term storage, contact NDDB for drought-relief feed programs',
      confidence: 'high',
    },
    researchBasis: {
      source: 'NDDB Fodder Availability and Drought Impact Data',
      url: 'https://nddb.coop/',
      specificFinding: 'Drought years (SPI < -1) see 20-40% increase in fodder prices in western India. Green fodder availability drops 30-50% during deficit monsoon periods',
      indiaValidation: 'NDDB cooperative data from Gujarat and Rajasthan confirms fodder price spikes of 20-40% in drought years — directly impacting dairy profitability',
      limitations: 'Fodder impact depends on baseline fodder production and storage — cooperatives with silage programs show less vulnerability',
    },
    testCases: [
      {
        description: 'Dairy district with SPI at -1.2 — fodder shortage triggers',
        inputs: { spi: -1.2 },
        expectedTriggered: true,
        expectedRiskDelta: 10,
        expectedReason: 'SPI below -1 — moderate drought impacting dairy through fodder shortage',
      },
      {
        description: 'Dairy district with SPI at 0.5 — adequate rainfall',
        inputs: { spi: 0.5 },
        expectedTriggered: false,
      },
    ],
    reviewDate: '2026-07-01',
  },
  {
    id: 'signal.spi.drought.poultry.water',
    version: '1.0.0',
    category: 'threshold',
    component: 'input_cost_pressure',
    sector: 'poultry',
    description: 'Poultry water scarcity — SPI below -1.5 creates water availability stress impacting poultry operations through increased water procurement costs',
    condition: {
      type: 'simple',
      variable: 'spi',
      operator: '<',
      value: -1.5,
    },
    effect: {
      riskDelta: 15,
      reason: 'SPI below -1.5 — water scarcity impacting poultry. Water procurement costs rising, bore wells running dry, and potential for water quality issues from alternate sources',
      recommendedAction: 'Install water storage tanks, ensure backup water supply arrangements, test alternate water sources for quality, reduce water-intensive operations if possible',
      confidence: 'medium',
    },
    researchBasis: {
      source: 'ICAR-Directorate of Poultry Research — Water Requirement Guidelines',
      url: 'https://icar-dpr.org.in/',
      specificFinding: 'Poultry require 250-350 ml/bird/day in hot conditions — water scarcity directly impacts feed intake and growth rate. Water restriction of 20% reduces feed intake by 30%',
      indiaValidation: 'Andhra Pradesh poultry belt experienced water crisis during 2015 drought — bore wells dried up, water tankers became primary source',
      limitations: 'Poultry operations with existing water storage and RO systems are less affected — vulnerability is highest for small-scale backyard poultry',
    },
    testCases: [
      {
        description: 'Poultry district with SPI at -1.8 — water scarcity triggers',
        inputs: { spi: -1.8 },
        expectedTriggered: true,
        expectedRiskDelta: 15,
        expectedReason: 'SPI below -1.5 — water scarcity impacting poultry',
      },
      {
        description: 'Poultry district with SPI at -0.9 — adequate water availability',
        inputs: { spi: -0.9 },
        expectedTriggered: false,
      },
    ],
    reviewDate: '2026-07-01',
  },
]
