import type { RuleRecord } from '../../schema'

export const RULES: RuleRecord[] = [
  {
    id: 'signal.thi.heat_stress.dairy.severe',
    version: '1.0.0',
    category: 'threshold',
    component: 'input_cost_pressure',
    sector: 'dairy',
    description: 'Severe heat stress — THI above 80 causes 10-25% yield drop, elevated feed intake, and increased veterinary costs in dairy cattle',
    condition: {
      type: 'simple',
      variable: 'thi',
      operator: '>',
      value: 80,
    },
    effect: {
      riskDelta: 25,
      reason: 'THI exceeds 80 — severe heat stress. Milk yield drops 10-25%, feed consumption rises 15-20%, and reproductive performance declines sharply',
      recommendedAction: 'Increase shaded water access, shift milking to early morning/evening, add electrolyte supplements to water, consider fans in housing area',
      confidence: 'high',
    },
    researchBasis: {
      source: 'NDDB Heat Stress Management Guidelines',
      url: 'https://nddb.coop/information/dairy-management',
      specificFinding: 'THI > 80 reduces milk yield 10-25% in crossbred cows; indigenous breeds show 5-15% reduction. Feed intake drops 10-20% above THI 80, compounding yield loss',
      indiaValidation: 'Validated across NDDB cooperative data in Gujarat and Rajasthan — peak summer THI consistently exceeds 80 in May-June in western India',
      limitations: 'Yield loss varies by breed — crossbred Holstein-Friesian more sensitive than indigenous Gir or Sahiwal',
    },
    testCases: [
      {
        description: 'Dairy farm in May with THI at 82 — severe heat stress triggers',
        inputs: { thi: 82 },
        expectedTriggered: true,
        expectedRiskDelta: 25,
        expectedReason: 'THI exceeds 80 — severe heat stress',
      },
      {
        description: 'Dairy farm in December with THI at 65 — no heat stress',
        inputs: { thi: 65 },
        expectedTriggered: false,
      },
    ],
    reviewDate: '2026-07-01',
  },
  {
    id: 'signal.thi.heat_stress.dairy.moderate',
    version: '1.0.0',
    category: 'threshold',
    component: 'input_cost_pressure',
    sector: 'dairy',
    description: 'Moderate heat stress — THI between 75-80 causes 5-10% yield decline and increased water consumption',
    condition: {
      type: 'band',
      variable: 'thi',
      min: 75,
      max: 80,
    },
    effect: {
      riskDelta: 15,
      reason: 'THI between 75-80 — moderate heat stress. Milk yield declining 5-10%, animals showing reduced feed intake and increased water consumption',
      recommendedAction: 'Ensure adequate clean water supply (80-120 L/day per animal), provide shade during peak sun hours, monitor for early signs of clinical heat stress',
      confidence: 'high',
    },
    researchBasis: {
      source: 'NDDB Heat Stress Management Guidelines',
      url: 'https://nddb.coop/information/dairy-management',
      specificFinding: 'THI 75-80 causes sub-clinical heat stress — 5-10% yield reduction, increased respiration rate, and elevated somatic cell count in milk',
      indiaValidation: 'Confirmed via NDDB cooperative data in Gujarat — sub-clinical losses accumulate across summer months even at moderate THI',
      limitations: 'Breed-specific variation not fully captured — some indigenous breeds tolerate THI 75+ without significant yield loss',
    },
    testCases: [
      {
        description: 'Dairy farm in June with THI at 77 — moderate heat stress triggers',
        inputs: { thi: 77 },
        expectedTriggered: true,
        expectedRiskDelta: 15,
        expectedReason: 'THI between 75-80 — moderate heat stress',
      },
      {
        description: 'Dairy farm in March with THI at 72 — no heat stress',
        inputs: { thi: 72 },
        expectedTriggered: false,
      },
    ],
    reviewDate: '2026-07-01',
  },
  {
    id: 'signal.thi.heat_stress.poultry.mortality',
    version: '1.0.0',
    category: 'threshold',
    component: 'input_cost_pressure',
    sector: 'poultry',
    description: 'Heat stress mortality risk — THI above 70 triggers significant poultry mortality and feed conversion efficiency loss',
    condition: {
      type: 'simple',
      variable: 'thi',
      operator: '>',
      value: 70,
    },
    effect: {
      riskDelta: 20,
      reason: 'THI exceeds 70 — poultry heat stress zone. Mortality rates rise sharply above THI 72, feed conversion ratio worsens 10-15%, and egg production drops in layers',
      recommendedAction: 'Activate evaporative cooling systems, reduce stocking density if possible, increase Vitamin C and electrolytes in feed, shift feeding to cooler hours',
      confidence: 'high',
    },
    researchBasis: {
      source: 'ICAR-Directorate of Poultry Research Guidelines',
      url: 'https://icar-dpr.org.in/',
      specificFinding: 'Poultry become heat-stressed above THI 70; mortality increases exponentially above THI 78. Broilers more susceptible than layers — mortality can reach 10-15% in severe episodes',
      indiaValidation: 'Validated against ICAR poultry mortality data from Andhra Pradesh and Tamil Nadu summer heat events',
      limitations: 'Modern broiler strains (Cobb, Ross) more heat-sensitive than desi breeds; open-sided housing mitigates THI impact vs enclosed systems',
    },
    testCases: [
      {
        description: 'Poultry farm in May with THI at 74 — heat stress mortality risk triggers',
        inputs: { thi: 74 },
        expectedTriggered: true,
        expectedRiskDelta: 20,
        expectedReason: 'THI exceeds 70 — poultry heat stress zone',
      },
      {
        description: 'Poultry farm in January with THI at 55 — no heat stress',
        inputs: { thi: 55 },
        expectedTriggered: false,
      },
    ],
    reviewDate: '2026-07-01',
  },
  {
    id: 'signal.thi.heat_stress.agriculture.crop_damage',
    version: '1.0.0',
    category: 'threshold',
    component: 'external_risk',
    sector: 'agriculture',
    description: 'Crop heat damage — THI above 85 indicates extreme heat conditions causing flower shedding, grain filling failure, and yield loss in field crops',
    condition: {
      type: 'simple',
      variable: 'thi',
      operator: '>',
      value: 85,
    },
    effect: {
      riskDelta: 15,
      reason: 'THI exceeds 85 — extreme heat conditions for crops. Risk of flower/fruit shedding, pollen sterility, accelerated crop maturity, and reduced grain weight',
      recommendedAction: 'Increase irrigation frequency, apply mulching to retain soil moisture, consider foliar spray of potassium bicarbonate to reduce transpiration loss',
      confidence: 'medium',
    },
    researchBasis: {
      source: 'ICAR-Crop Physiology Division — Heat Stress in Crops',
      url: 'https://icar.org.in/',
      specificFinding: 'Wheat yields drop 4-8% per degree rise above 34°C during reproductive stage. Rice spikelet sterility increases sharply above 35°C — heat stress during flowering causes 10-30% yield loss',
      indiaValidation: 'Wheat belt in Punjab/Haryana shows measurable yield decline when March temperatures exceed 35°C for consecutive days',
      limitations: 'Crop-specific — heat tolerance varies widely between wheat, rice, pulses, and oilseeds. Irrigated vs rainfed makes a significant difference',
    },
    testCases: [
      {
        description: 'Wheat farm during flowering stage with THI at 88 — crop heat damage triggers',
        inputs: { thi: 88 },
        expectedTriggered: true,
        expectedRiskDelta: 15,
        expectedReason: 'THI exceeds 85 — extreme heat conditions for crops',
      },
      {
        description: 'Rice farm in monsoon with THI at 68 — no heat damage',
        inputs: { thi: 68 },
        expectedTriggered: false,
      },
    ],
    reviewDate: '2026-07-01',
  },
]
