import type { RuleRecord } from '../schema'

export const RULES: RuleRecord[] = [
  {
    id: 'component.income_stability.volatile',
    version: '1.0.0',
    category: 'threshold',
    component: 'income_stability',
    description: 'Income CV above 0.75 — highly volatile income makes EMI planning unreliable and increases default risk.',
    condition: {
      type: 'simple',
      variable: 'income_cv',
      operator: '>',
      value: 0.75,
    },
    effect: {
      riskDelta: 30,
      reason: 'Highly volatile income (CV > 0.75). Monthly income swings make consistent EMI payments unreliable — even profitable months may not cover obligations.',
      recommendedAction: 'Switch to flexible EMI product (step-up or seasonal repayment). Build 3-month emergency fund during peak income months.',
      confidence: 'high',
    },
    researchBasis: {
      source: 'M-PESA / CGAP – Transaction Regularity Research (2019)',
      url: 'https://www.cgap.org/research/publication/transaction-data-small-enterprise',
      specificFinding: 'Transaction regularity (low CV) is a stronger predictor of repayment than absolute income level. High-CV enterprises show significantly higher default rates.',
      indiaValidation: 'Validated across M-PESA Kenya and Indian MFI portfolio data from SKS/Bandhan.',
      limitations: 'CV calculated on 12-month window; enterprises with <6 months history may have unreliable CV.',
    },
    testCases: [
      {
        description: 'Seasonal crop trader with CV 0.85 — highly volatile',
        inputs: { income_cv: 0.85 },
        expectedTriggered: true,
        expectedRiskDelta: 30,
        expectedReason: 'Highly volatile income',
      },
      {
        description: 'Dairy cooperative member with CV 0.40 — moderate',
        inputs: { income_cv: 0.40 },
        expectedTriggered: false,
      },
    ],
    reviewDate: '2026-07-01',
  },
  {
    id: 'component.income_stability.moderate',
    version: '1.0.0',
    category: 'threshold',
    component: 'income_stability',
    description: 'Income CV above 0.50 — moderate variation creates occasional EMI shortfall risk.',
    condition: {
      type: 'simple',
      variable: 'income_cv',
      operator: '>',
      value: 0.50,
    },
    effect: {
      riskDelta: 15,
      reason: 'Moderate income variation (CV > 0.50). Some months may not cover EMI obligations, requiring savings buffer or informal borrowing.',
      recommendedAction: 'Maintain 2-month EMI buffer in savings. Track monthly income closely and trigger early warning when below threshold.',
      confidence: 'medium',
    },
    researchBasis: {
      source: 'CGAP – Financial Diaries of Smallholder Farmers (2022)',
      specificFinding: 'Households with income CV 0.4-0.6 showed 28% higher likelihood of informal borrowing to meet fixed obligations compared to stable-income peers.',
      indiaValidation: 'Study covered 240 farming households in Maharashtra and Madhya Pradesh.',
      limitations: 'Informal borrowing is not always captured in standard financial metrics.',
    },
    testCases: [
      {
        description: 'Mixed dairy-retail with CV 0.55 — moderate variation',
        inputs: { income_cv: 0.55 },
        expectedTriggered: true,
        expectedRiskDelta: 15,
        expectedReason: 'Moderate income variation',
      },
      {
        description: 'Dairy farmer with CV 0.25 — stable',
        inputs: { income_cv: 0.25 },
        expectedTriggered: false,
      },
    ],
    reviewDate: '2026-07-01',
  },
  {
    id: 'component.income_stability.slight_variation',
    version: '1.0.0',
    category: 'threshold',
    component: 'income_stability',
    description: 'Income CV above 0.30 — some variation present, warrants monitoring.',
    condition: {
      type: 'simple',
      variable: 'income_cv',
      operator: '>',
      value: 0.30,
    },
    effect: {
      riskDelta: 5,
      reason: 'Slight income variation (CV > 0.30). Generally manageable but requires attention during seasonal troughs.',
      recommendedAction: 'Continue monitoring. No immediate action required unless CV is trending upward.',
      confidence: 'low',
    },
    researchBasis: {
      source: 'M-PESA / CGAP – Transaction Regularity Research (2019)',
      specificFinding: 'CV between 0.2-0.4 is the "normal" range for most small enterprises with mixed income streams. Minimal default impact.',
      indiaValidation: 'Consistent with Indian rural micro-enterprise income patterns across states.',
      limitations: 'Individual variation is high in this range; context matters more than the number.',
    },
    testCases: [
      {
        description: 'Dairy farmer with CV 0.35 — slight variation',
        inputs: { income_cv: 0.35 },
        expectedTriggered: true,
        expectedRiskDelta: 5,
        expectedReason: 'Slight income variation',
      },
      {
        description: 'Salaried side-income with CV 0.10 — very stable',
        inputs: { income_cv: 0.10 },
        expectedTriggered: false,
      },
    ],
    reviewDate: '2026-07-01',
  },
  {
    id: 'component.income_stability.consistent',
    version: '1.0.0',
    category: 'threshold',
    component: 'income_stability',
    description: 'Income CV at or below 0.15 — highly consistent income stream, strong indicator of repayment reliability.',
    condition: {
      type: 'simple',
      variable: 'income_cv',
      operator: '<=',
      value: 0.15,
    },
    effect: {
      riskDelta: -10,
      reason: 'Highly consistent income (CV <= 0.15). Predictable cash flow makes EMI planning reliable — strong repayment indicator.',
      recommendedAction: 'Eligible for pre-approved credit products. Consider longer-tenure loans at better rates given predictable income.',
      confidence: 'medium',
    },
    researchBasis: {
      source: 'M-PESA / CGAP – Transaction Regularity Research (2019)',
      specificFinding: 'Enterprises with CV < 0.15 are consistently associated with much lower default rates compared to the highest volatility quintile. Transaction regularity is a strong predictor of repayment.',
      indiaValidation: 'Applied to Indian MFI portfolio analysis across Andhra Pradesh, Tamil Nadu, and Karnataka.',
      limitations: 'Very low CV may also indicate stagnant growth — not always positive.',
    },
    testCases: [
      {
        description: 'Cooperative dairy member with CV 0.12 — highly consistent',
        inputs: { income_cv: 0.12 },
        expectedTriggered: true,
        expectedRiskDelta: -10,
        expectedReason: 'Highly consistent income',
      },
      {
        description: 'Seasonal trader with CV 0.45 — not consistent',
        inputs: { income_cv: 0.45 },
        expectedTriggered: false,
      },
    ],
    reviewDate: '2026-07-01',
  },
  {
    id: 'component.income_stability.stable',
    version: '1.0.0',
    category: 'ratio_band',
    component: 'income_stability',
    description: 'Income CV between 0.15 and 0.30 — stable with minor seasonal variation.',
    condition: { type: 'band', variable: 'income_cv', min: 0.15, max: 0.30 },
    effect: {
      riskDelta: -5,
      reason: 'Income is stable with minor seasonal variation. Consistent enough for reliable EMI planning.',
      recommendedAction: 'Maintain current income mix. Consider diversifying to reduce seasonal dependency.',
      confidence: 'medium',
    },
    researchBasis: {
      source: 'CGAP (2024) Leveraging Transactional Data for MSE Lending',
      specificFinding: 'CV between 0.15-0.30 represents stable income with seasonal variation. CGAP research indicates AUC ~0.70 for transactional data in this range.',
      indiaValidation: 'Consistent with Indian rural enterprise income patterns.',
      limitations: 'CV calculation requires 6+ months of data for reliability.',
    },
    testCases: [
      { description: 'CV 0.20 — stable', inputs: { income_cv: 0.20 }, expectedTriggered: true, expectedRiskDelta: -5, expectedReason: 'stable with minor variation' },
      { description: 'CV 0.35 — slight variation', inputs: { income_cv: 0.35 }, expectedTriggered: false },
    ],
    reviewDate: '2026-07-01',
  },
]
